### ISSUE TITLE
blue (2 tones) and yellow color when use modes

### ISSUE THREAD

**Issue by sl1pkn07** [Nlzy/vapoursynth-waifu2x-ncnn-vulkan#1] opened 2020-02-26 13:18 UTC
image test:
<details>

![test](https://user-images.githubusercontent.com/462213/75347929-206a3900-58a2-11ea-8549-ed1b49848a53.png)

</details>
mode=0
<details>

![Screenshot_20200226_141532](https://user-images.githubusercontent.com/462213/75348119-7fc84900-58a2-11ea-914b-2f2e26e5cdfa.png)

</details>
mode=1
<details>

![Screenshot_20200226_141616](https://user-images.githubusercontent.com/462213/75348177-97073680-58a2-11ea-9e92-910c12ff966c.png)

</details>
mode=2
<details>

![Screenshot_20200226_141655](https://user-images.githubusercontent.com/462213/75348209-a8504300-58a2-11ea-9bda-57429acf93f6.png)

</details>

builded on archlinux
https://aur.archlinux.org/packages/vapoursynth-plugin-waifu2x-ncnn-vulkan-git/

EDIT: Dual Xeon E5-2560-V4 ES + RTX 2060 (Vulkan drivers 440.58.02)

**Comment by 4re** [comment] 2020-02-26 14:45
I'm having the same problem on a Gentoo Linux. Tested with different versions of `ncnn` making no difference (Live and the three last releases).

EDIT:  i5-6600K CPU + GeForce RTX 2080 (440.59 proprietary drivers)

**Comment by nlzy** [comment] 2020-02-26 22:16
Seems like a bug in NCNN, try to use `precision=32` option.
I don't have any RTX 2000 series graphics card, so I can't reproduce the bug.

P.S. I highly recommend NVIDIA users to use [vapoursynth-waifu2x-caffe](https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe) because it has better performance, better precision, and supports more models.

**Comment by sl1pkn07** [comment] 2020-02-27 12:14
testing with https://github.com/nihui/waifu2x-ncnn-vulkan command line (builded with same ncnn library as the plugin)

works as expected

~~~
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[~/aplicaciones/vapoursynth-test]|
└───╼  waifu2x-ncnn-vulkan 
Usage: waifu2x-ncnn-vulkan -i infile -o outfile [options]...

  -h                   show this help
  -v                   verbose output
  -i input-path        input image path (jpg/png) or directory
  -o output-path       output image path (png) or directory
  -n noise-level       denoise level (-1/0/1/2/3, default=0)
  -s scale             upscale ratio (1/2, default=2)
  -t tile-size         tile size (>=32, default=400)
  -m model-path        waifu2x model path (default=models-cunet)
  -g gpu-id            gpu device to use (default=0)
  -j load:proc:save    thread count for load/proc/save (default=1:2:2)
┌─┤[$]|[sl1pkn07]|[sL1pKn07]|[~/aplicaciones/vapoursynth-test]|
└───╼  waifu2x-ncnn-vulkan  -i test.png -o testx2.png
[0 GeForce RTX 2060]  queueC=2[8]  queueG=0[16]  queueT=1[2]  buglssc=0
[0 GeForce RTX 2060]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
~~~

<details>

![testx2](https://user-images.githubusercontent.com/462213/75443934-bb2a4c80-5962-11ea-9e0c-d06d1a5e06b5.png)

</details>

**Comment by nlzy** [comment] 2020-02-27 13:04
`waifu2x-ncnn-vulkan` command line use int8. For precision, this plugin switched to float16 since R2. If waifu2x-ncnn-vulkan is ok, R1 should be ok.

Could you edit https://github.com/nihui/waifu2x-ncnn-vulkan/blob/master/src/waifu2x.cpp#L52 to `false` then try it again?

**Comment by sl1pkn07** [comment] 2020-02-27 13:28
done

~~~patch
diff --git a/src/waifu2x.cpp b/src/waifu2x.cpp
index 0fb85af..d36c3d4 100644
--- a/src/waifu2x.cpp
+++ b/src/waifu2x.cpp
@@ -49,7 +49,7 @@ Waifu2x::Waifu2x(int gpuid, bool _tta_mode)
     net.opt.use_fp16_packed = true;
     net.opt.use_fp16_storage = true;
     net.opt.use_fp16_arithmetic = false;
-    net.opt.use_int8_storage = true;
+    net.opt.use_int8_storage = false;
     net.opt.use_int8_arithmetic = false;
 
     net.set_vulkan_device(gpuid);
~~~

~~~
└───╼  waifu2x-ncnn-vulkan -i test.png -o testx2.png
[0 GeForce RTX 2060]  queueC=2[8]  queueG=0[16]  queueT=1[2]  buglssc=0
[0 GeForce RTX 2060]  fp16p=1  fp16s=1  fp16a=1  int8s=1  int8a=1
~~~
<details>

![testx2](https://user-images.githubusercontent.com/462213/75449430-3bee4600-596d-11ea-9ade-e65b14bf6722.png)

</details>

**Comment by sl1pkn07** [comment] 2020-02-27 13:45
R1 i can't build it because waifu2x-ncnn-vulkan (from git) don't build any lib. only executable

**Comment by sl1pkn07** [comment] 2020-02-27 14:12
R1 fails build

~~~
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found Vulkan: /usr/lib/libvulkan.so  
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "Findw2xnvk.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "w2xnvk", but
  CMake did not find one.

  Could not find a package configuration file provided by "w2xnvk" with any
  of the following names:

    w2xnvkConfig.cmake
    w2xnvk-config.cmake

  Add the installation prefix of "w2xnvk" to CMAKE_PREFIX_PATH or set
  "w2xnvk_DIR" to a directory containing one of the above files.  If "w2xnvk"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/tmp/makepkg/vapoursynth-plugin-waifu2x-ncnn-vulkan-git/src/build/CMakeFiles/CMakeOutput.log".
~~~

seems waifu2x-ncnn-vulkan not provide any .cmake files for configure it

**Comment by nlzy** [comment] 2020-02-27 14:26
`waifu2x-ncnn-vulkan` used in R1 is a fork, isn't original source tree. Sorry I forgot this. The fork used at that time has been deleted, so we can't build R1 anymore.

**Comment by nlzy** [comment] 2020-02-27 14:32
I noticed that the issue you mentioned is `vapoursynth-waifu2x-w2xc`, and I suggest using `vapoursynth-waifu2x-caffe`

**Comment by 4re** [comment] 2020-02-27 15:10
That was my gaming PC, on the one I use to encode I have same issues:
`AMD Ryzen 7 1700` + `Radeon RX 480`

**Comment by 4re** [comment] 2020-02-27 15:10
That was my gaming PC, on the one I use to encode I have same issues:
`AMD Ryzen 7 1700` + `Radeon RX 480`

**Comment by sl1pkn07** [comment] 2020-02-27 15:28
as note, tested with other source plugin (imwri). also have same output

**Comment by nlzy** [comment] 2020-02-27 15:57
> That was my gaming PC, on the one I use to encode I have same issues:
> `AMD Ryzen 7 1700` + `Radeon RX 480`

What operating system and driver are you using on the `RX 480`?

**Comment by nlzy** [comment] 2020-02-27 16:09
I am working on this issue, it may take a few days.

**Comment by 4re** [comment] 2020-02-27 18:27
Open source drivers on `Gentoo Linux`, `kernel 5.5.4`, `mesa 20.0.0`.

**Comment by nlzy** [comment] 2020-06-06 11:38
Reproduced. This problem is caused by incorrect decimal point parsing in NCNN.

Same reason as https://github.com/nihui/waifu2x-ncnn-vulkan/issues/59 . Fixed in https://github.com/Tencent/ncnn/commit/13c59d9ad262e9811019b9662f1c3d2fe3b6e7e6 by upstream.

Recompile with laest NCNN should work now.

Thanks for reporting.

**Closed as completed** 2020-06-18 01:17 UTC
Labels: bug
